import requests
import re
import base64
from html import escape
from html import unescape
import os
import sys
from typing import Dict, Optional
import json

# === CONFIGURATION ===
WP_SITE = "https://www.fio.ie/wp-json/wp/v2/" # WordPress REST API URL
USERNAME = os.getenv("WORDPRESS_USERNAME")  # WordPress username
APPLICATION = os.getenv("WORDPRESS_APPLICATION")  # App password from WordPress
UNSPLASH_API_KEY = os.getenv("UNSPLASH_API_KEY")
YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY")  # YouTube Data API key


class OpenAIProvider:  # pylint: disable=too-few-public-methods
    """
    This class provides a way to interact with the OpenAI API for text completion tasks.

    Attributes:
    - api_key (str): The API key used for authentication with the OpenAI API.
    - endpoint (str): The URL endpoint for making requests to the OpenAI API.
    - model (str): The model identifier used for text completion tasks.

    Methods:
    - improve_text(prompt: str, text: str) -> str: Sends a text completion request to the OpenAI API using the provided
    prompt and text, and returns the improved text response.
    """

    def __init__(self) -> None:
        """
        Initialize the API key, endpoint, and model for OpenAI chat completions.

        Arguments:
        - self: The object instance.
        """
        self.api_key: str = os.getenv("AI_API_KEY")
        self.endpoint: str = "https://api.openai.com/v1/chat/completions"
        self.model: str = os.getenv("AI_MODEL")

    def improve_text(self, prompt: str, text: str) -> str:
        """
        Improve the given text by providing a more coherent response using the OpenAI API.

        Arguments:
        - prompt (str): The prompt to be used for generating a response.
        - text (str): The original text that needs improvement.

        Return:
        - str: The improved text generated by the OpenAI API.

        Exceptions:
        - requests.exceptions.RequestException: Raised for any request-related exceptions like network issues or
        timeouts.
        """
        headers: Dict[str, str] = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }

        body: Dict = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": prompt},
                {"role": "user", "content": text},
            ],
            "temperature": 0.4,
        }

        try:
            # Make the API request
            response: requests.Response = requests.post(
                self.endpoint, json=body, headers=headers, timeout=120
            )

            # Check for successful response
            if response.status_code == 200:
                return response.json()[
                    "choices"][0]["message"]["content"].strip()

            # If the request fails, raise an error with the response details
            print(
                f"OpenAI API call failed: {response.status_code} - {response.text}")
            sys.exit(1)
        except requests.exceptions.RequestException as e:
            # Catch any request-related exceptions (e.g., network issues,
            # timeouts)
            print(f"Request failed: {str(e)}")
            sys.exit(1)


def search_image_url_unsplash(query: str, api_key: str) -> Optional[str]:
    url = "https://api.unsplash.com/search/photos"
    headers = {
        "Accept-Version": "v1",
        "Authorization": f"Client-ID {api_key}"
    }
    params = {
        "query": query,
        "orientation": "landscape",
        "per_page": 1
    }
    response = requests.get(url, headers=headers, params=params)
    if response.status_code == 200:
        data = response.json()
        if data["results"]:
            return data["results"][0]["urls"]["regular"]
    else:
        print(f"Unsplash API error: {response.status_code} - {response.text}")
    return None


def upload_image_to_wordpress(image_url: str, image_name: str) -> Optional[str]:
    try:
        img_data = requests.get(image_url).content
        media_url = f"{WP_SITE}media"
        headers = {
            "Content-Disposition": f"attachment; filename={image_name}",
            "Content-Type": "image/jpeg",
            "Authorization": f'Basic {base64.b64encode(f"{USERNAME}:{APPLICATION}".encode()).decode()}',
        }
        response = requests.post(media_url, headers=headers, data=img_data)
        if response.status_code == 201:
            return response.json().get("source_url")
        else:
            print(f"WordPress upload failed: {response.status_code} - {response.text}")
    except Exception as e:
        print(f"Image upload failed: {e}")
    return None



def search_youtube_video(topic: str, api_key: str) -> Optional[str]:
    url = "https://www.googleapis.com/youtube/v3/search"
    params = {
        "part": "snippet",
        "q": topic,
        "type": "video",
        "maxResults": 1,
        "videoEmbeddable": "true",
        "key": api_key
    }
    response = requests.get(url, params=params)
    if response.status_code == 200:
        data = response.json()
        if data["items"]:
            return f"https://www.youtube.com/embed/{data['items'][0]['id']['videoId']}"
    return None




def search_image_url_unsplash(query: str, api_key: str) -> Optional[str]:
    url = "https://api.unsplash.com/search/photos"
    headers = {"Authorization": f"Client-ID {api_key}"}
    params = {"query": query, "per_page": 1, "orientation": "landscape"}
    response = requests.get(url, headers=headers, params=params)
    if response.status_code == 200:
        data = response.json()
        if data["results"]:
            return data["results"][0]["urls"]["regular"]
    return None



def get_auth_header() -> dict:
    token = base64.b64encode(f"{USERNAME}:{APPLICATION}".encode()).decode()

    return {
        "Authorization": f"Basic {token}",
        "Content-Type": "application/json"
    }

# === Convert <pre class="lang:..."> blocks to <pre><code class="language-..."> ===
def convert_pre_tags(html: str) -> str:
    pattern = r'<pre\s+[^>]*class=["\']lang:(\w+)["\'][^>]*>(.*?)</pre>'
    
    def repl(match):
        lang = match.group(1).lower()
        code = match.group(2).strip()
        return f'<pre><code class="language-{lang}">{escape(code)}</code></pre>'

    return re.sub(pattern, repl, html, flags=re.DOTALL | re.IGNORECASE)

# === Process one post/page ===
def process_post(post: dict) -> tuple[bool, dict]:
    content = post.get("content", {}).get("rendered", "")
    
    # Step 1: Decode all HTML entities everywhere
    content = unescape(content)

    # Step 2: Replace legacy code block syntax
    content = convert_pre_tags(content)

    post["content"] = {"raw": content}

    return post


def append_enrichment_to_post(content: str, video_url: Optional[str]) -> str:
    enrichment = ""
    if video_url:
        enrichment = "\n\n<hr><h2>📚 Further Learning</h2>\n"
        enrichment += f'<p>🎥 Watch this video for more:</p>\n<iframe width="710" height="415" src="{video_url}" frameborder="0" allowfullscreen></iframe>\n'
    return content + enrichment


def enrich_post_with_ai(post: dict, ai: OpenAIProvider, unsplash_api_key: str, youtube_api_key: str) -> dict:
    title = post["title"]["rendered"]
    content = post["content"]['raw']
    
    prompt = """You're helping enrich a blog post with multimedia. 
Based on the following blog content, suggest:
1. image_idea: A vivid description of a related image that could visually represent this post.
2. youtube_topics: Two short YouTube video topics relevant to the post's content.

Return in this format:
image_idea: ...
youtube_topics: topic for first video, topic for second video
"""
    ai_response = ai.improve_text(prompt, content)

    # === Parse AI response
    image_idea = None
    youtube_topics = []

    for line in ai_response.splitlines():
        if line.lower().startswith("image_idea:"):
            image_idea = line.split(":", 1)[1].strip()
        elif line.lower().startswith("youtube_topics:"):
            youtube_topics = [t.strip() for t in line.split(":", 1)[1].split(",")]

    # === Image enrichment
    featured_image_url = None
    if image_idea:
        unsplash_url = search_image_url_unsplash(image_idea, unsplash_api_key)
        if unsplash_url:
            image_name = title.replace(" ", "_") + ".jpg"
            featured_image_url = upload_image_to_wordpress(unsplash_url, image_name)

    # === YouTube enrichment
    video_url = None
    for topic in youtube_topics:
        video_url = search_youtube_video(topic, youtube_api_key)
        if video_url:
            break

    enriched_content = append_enrichment_to_post(content, video_url)

    post["content"] = {"raw": enriched_content}

    if featured_image_url:
        img_data = requests.get(featured_image_url).content
        media_url = f"{WP_SITE}media"
        headers = get_auth_header()
        headers.update({
            "Content-Disposition": f"attachment; filename={title}.jpg",
            "Content-Type": "image/jpeg"
        })
        media_response = requests.post(media_url, headers=headers, data=img_data)
        if media_response.status_code == 201:
            media_id = media_response.json().get("id")
            post["featured_media"] = media_id

    return post


def update_posts(items, ai_provider, post_type: str):

    for post in items:
        # Process and enrich the post
        updated_content = process_post(post)
        enriched_post = enrich_post_with_ai(updated_content, ai_provider, UNSPLASH_API_KEY, YOUTUBE_API_KEY)

        # Prepare the payload with only the fields to update
        payload = {
            "content": enriched_post["content"]["raw"]
        }
        if "featured_media" in enriched_post:
            payload["featured_media"] = enriched_post["featured_media"]

        # Send the update request
        update_url = f"{WP_SITE}{post_type}/{post['id']}"
        result = requests.put(update_url, json=payload, headers=get_auth_header())

        if result.status_code == 200:
            print(f"✅ Successfully updated {post_type} ID {post['id']}: {post['title']['rendered']}")
        else:
            print(f"❌ Failed to update {post_type} ID {post['id']}: {result.text}")


# === Fetch and update posts/pages ===
def update_content(post_type: str):
    ai_provider = OpenAIProvider()
    page = 1
    while True:
        url = f"{WP_SITE}{post_type}?per_page=100&page={page}"
        response = requests.get(url, headers=get_auth_header())
        if response.status_code != 200:
            print(f"⚠️ Failed to fetch {post_type} (page {page}): {response.status_code}")
            break

        items = response.json()
        if not items:
            break
    
        update_posts(items, ai_provider, post_type)

        page += 1
        return

# === Main ===
if __name__ == "__main__":
    update_content("posts")
    sys.exit(0)
    update_content("pages")